import Image from 'next/image';
import { Fragment, type ElementType } from 'react';

import { cn } from '@/utils/cn';

/*
 * Brand elements from the identity sheet (identidade_fernandoosman_portfolio/):
 * the FO mark, the two-tone wordmark (navy first name, blue surname), the
 * tagline with teal dots and the "Science / Insight / Impact" motto.
 * Image files are generated by `npm run brand:assets`.
 */

const LOGO_RATIO = 269 / 160;

/** The FO mark on a light background (transparent PNG). */
export function LogoMark({
  height = 32,
  className,
  priority = false,
}: {
  height?: number;
  className?: string;
  priority?: boolean;
}) {
  return (
    <Image
      src="/brand/fo-logo.png"
      alt=""
      width={Math.round(height * LOGO_RATIO)}
      height={height}
      unoptimized
      priority={priority}
      className={cn('shrink-0', className)}
    />
  );
}

/** The app icon (FO on a navy rounded square), for dark surfaces and small sizes. */
export function BrandIcon({ size = 32, className }: { size?: number; className?: string }) {
  return (
    <Image
      src="/brand/fo-icon.png"
      alt=""
      width={size}
      height={size}
      unoptimized
      className={cn('shrink-0', className)}
    />
  );
}

/**
 * "FERNANDO OSMAN": every word but the last in navy, the last in blue, in
 * spaced capitals. Works for any name set in the profile.
 */
export function Wordmark({
  name,
  as: Tag = 'span',
  className,
  id,
}: {
  name: string;
  as?: ElementType;
  className?: string;
  id?: string;
}) {
  const words = name.trim().split(/\s+/).filter(Boolean);
  const last = words.length > 1 ? words.pop() : undefined;
  return (
    <Tag id={id} className={cn('wordmark text-navy-900', className)}>
      {words.join(' ')}
      {last ? <span className="text-azure-600"> {last}</span> : null}
    </Tag>
  );
}

/** "Clinical Research • Medical Affairs • Data Analysis", with teal dots. */
export function Tagline({ items, className }: { items: string[]; className?: string }) {
  if (items.length === 0) return null;
  return (
    <p className={cn('tracking-[0.06em] text-navy-800', className)}>
      {items.map((item, index) => (
        <Fragment key={item}>
          {/* Lines may break between items (at the spaces), never inside one. */}
          {index > 0 ? (
            <>
              {' '}
              <span aria-hidden="true" className="mx-1 text-teal-500">
                •
              </span>{' '}
            </>
          ) : null}
          <span className="inline-block max-w-full">{item}</span>
        </Fragment>
      ))}
    </p>
  );
}

/** The brand sign-off: Science / Insight / Impact, set between two rules. */
export function Motto({ className }: { className?: string }) {
  const words = ['Science', 'Insight', 'Impact'];
  return (
    <div className={cn('flex items-center gap-4', className)}>
      <span className="h-px flex-1 bg-rule" aria-hidden="true" />
      <p className="text-xs font-medium tracking-[0.32em] text-navy-800 uppercase">
        {words.map((word, index) => (
          <span key={word}>
            {index > 0 ? (
              <span aria-hidden="true" className="mx-3 text-teal-500">
                /
              </span>
            ) : null}
            {word}
          </span>
        ))}
      </p>
      <span className="h-px flex-1 bg-rule" aria-hidden="true" />
    </div>
  );
}
