#!/usr/bin/env node
// Generates db/seed.sql from the sample content in this folder.
// Usage: npm run seed:generate
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { articles } from './articles.mjs';
import { categories, projects, settings, siteProfile, topics } from './catalog.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(here, '../../db/seed.sql');

/** Quotes a value as a standard SQL string literal (standard_conforming_strings = on). */
const str = (value) => (value === null || value === undefined ? 'null' : `'${String(value).replaceAll("'", "''")}'`);
const json = (value) => `${str(JSON.stringify(value))}::jsonb`;
const textArray = (values) => `array[${values.map(str).join(', ')}]::text[]`;
const slugify = (value) =>
  value
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 120);

const lines = [];
const emit = (sql = '') => lines.push(sql);

emit('-- =============================================================================');
emit('-- Sample data. GENERATED by scripts/seed/generate-seed.mjs — do not edit by hand.');
emit('-- Safe to run more than once: existing rows (matched by slug/key) are kept.');
emit('-- =============================================================================');
emit('begin;');
emit();

emit('-- Topics');
for (const [index, topic] of topics.entries()) {
  emit(
    `insert into public.topics (name, name_pt, slug, description, description_pt, icon, sort_order) values (${str(topic.name)}, ${str(topic.name_pt ?? '')}, ${str(topic.slug)}, ${str(topic.description)}, ${str(topic.description_pt ?? '')}, ${str(topic.icon)}, ${index + 1}) on conflict (slug) do nothing;`,
  );
}
emit();

emit('-- Categories');
for (const [index, category] of categories.entries()) {
  emit(
    `insert into public.categories (name, name_pt, slug, description, sort_order) values (${str(category.name)}, ${str(category.name_pt ?? '')}, ${str(category.slug)}, ${str(category.description)}, ${index + 1}) on conflict (slug) do nothing;`,
  );
}
emit();

emit('-- Site profile (single row)');
emit(
  `insert into public.site_profile (id, full_name, headline, focus_areas, short_bio, bio, course, university, current_semester, total_semesters, location, languages, interests, education, experience, skills, certifications)
values (1, ${str(siteProfile.full_name)}, ${str(siteProfile.headline)}, ${textArray(siteProfile.focus_areas)}, ${str(siteProfile.short_bio)}, ${str(siteProfile.bio)}, ${str(siteProfile.course)}, ${str(siteProfile.university)}, ${siteProfile.current_semester}, ${siteProfile.total_semesters}, ${str(siteProfile.location)}, ${json(siteProfile.languages)}, ${textArray(siteProfile.interests)}, ${json(siteProfile.education)}, ${json(siteProfile.experience)}, ${json(siteProfile.skills)}, ${json(siteProfile.certifications)})
on conflict (id) do nothing;`,
);
emit();

emit('-- Settings');
for (const setting of settings) {
  emit(
    `insert into public.settings (key, value, is_public) values (${str(setting.key)}, ${json(setting.value)}, ${setting.is_public}) on conflict (key) do nothing;`,
  );
}
emit();

const allTags = new Map();
for (const item of [...articles, ...projects]) {
  for (const name of item.tags) allTags.set(slugify(name), name);
}
emit('-- Tags');
for (const [slug, name] of allTags) {
  emit(`insert into public.tags (name, slug) values (${str(name)}, ${str(slug)}) on conflict (slug) do nothing;`);
}
emit();

const firstAdmin = "(select p.id from public.profiles p where p.role = 'admin' and p.is_active order by p.created_at limit 1)";

emit('-- Articles');
for (const article of articles) {
  const status = article.status ?? 'published';
  const publishedAt = status === 'published' ? str(article.publishedAt) : 'null';
  emit(
    `insert into public.articles (title, slug, subtitle, excerpt, content, status, featured, language, category_id, seo_description, published_at, author_id)
values (${str(article.title)}, ${str(article.slug)}, ${str(article.subtitle)}, ${str(article.excerpt)}, ${json(article.content)}, ${str(status)}, ${article.featured}, ${str(article.language)}, (select c.id from public.categories c where c.slug = ${str(article.category)}), ${str(article.seoDescription)}, ${publishedAt}, ${firstAdmin})
on conflict (slug) do nothing;`,
  );
  emit(
    `insert into public.article_topics (article_id, topic_id) select a.id, t.id from public.articles a join public.topics t on t.slug in (${article.topics.map(str).join(', ')}) where a.slug = ${str(article.slug)} on conflict do nothing;`,
  );
  emit(
    `insert into public.article_tags (article_id, tag_id) select a.id, t.id from public.articles a join public.tags t on t.slug in (${article.tags.map((tag) => str(slugify(tag))).join(', ')}) where a.slug = ${str(article.slug)} on conflict do nothing;`,
  );
  for (const [position, reference] of article.references.entries()) {
    emit(
      `insert into public.article_references (article_id, position, title, authors, journal, year, doi, url) select a.id, ${position}, ${str(reference.title)}, ${str(reference.authors ?? '')}, ${str(reference.journal ?? '')}, ${reference.year ?? 'null'}, ${str(reference.doi)}, ${str(reference.url)} from public.articles a where a.slug = ${str(article.slug)} and not exists (select 1 from public.article_references r where r.article_id = a.id and r.position = ${position});`,
    );
  }
  emit();
}

emit('-- Projects');
for (const project of projects) {
  emit(
    `insert into public.projects (title, slug, summary, content, status, progress, technologies, started_on, completed_on, featured, sort_order, published_at, author_id)
values (${str(project.title)}, ${str(project.slug)}, ${str(project.summary)}, ${json(project.content)}, 'published', ${str(project.progress)}, ${textArray(project.technologies)}, ${str(project.started_on)}, ${str(project.completed_on)}, ${project.featured}, ${project.sort_order}, now(), ${firstAdmin})
on conflict (slug) do nothing;`,
  );
  emit(
    `insert into public.project_tags (project_id, tag_id) select p.id, t.id from public.projects p join public.tags t on t.slug in (${project.tags.map((tag) => str(slugify(tag))).join(', ')}) where p.slug = ${str(project.slug)} on conflict do nothing;`,
  );
}
emit();

emit('-- Plain-text projection and reading time (the app recomputes both on every save).');
for (const table of ['articles', 'projects']) {
  emit(
    `update public.${table} set content_text = coalesce((select string_agg(v #>> '{}', ' ') from jsonb_path_query(content, 'strict $.**.text') as v), '') where content_text = '';`,
  );
}
emit(
  `update public.articles set reading_time = greatest(1, ceil(coalesce(array_length(regexp_split_to_array(btrim(content_text), '\\s+'), 1), 0) / 220.0)::integer) where content_text <> '';`,
);
emit();
emit('commit;');
emit();

writeFileSync(outputPath, lines.join('\n'), 'utf8');
console.log(`Wrote ${outputPath}`);
