-- =============================================================================
-- 0500 · Storage buckets
-- =============================================================================
-- documents        PRIVATE · PDFs only · 30 MB  → served exclusively through
--                  short-lived signed URLs generated by the server.
-- article-images   PUBLIC  · raster images      → cover images and inline figures
-- profile-images   PUBLIC  · raster images      → profile photo
-- project-images   PUBLIC  · raster images      → project covers and galleries
--
-- No storage.objects policies are created for anon/authenticated: with RLS on
-- storage.objects that means browsers cannot list, read (private bucket),
-- upload, overwrite or delete anything directly. Every write goes through the
-- Next.js server, which authenticates the admin, validates the file and then
-- uses the service role. PDF uploads use one-time signed upload URLs that the
-- server issues for a random path it chose itself.
--
-- To change the PDF size limit, update both `file_size_limit` below and
-- PDF_MAX_SIZE_MB in the environment (see src/config/uploads.ts).
-- SVG is deliberately not allowed in any bucket (it can carry scripts).
-- =============================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('documents', 'documents', false, 31457280, array['application/pdf']),
  ('article-images', 'article-images', true, 5242880, array['image/jpeg', 'image/png', 'image/webp', 'image/avif', 'image/gif']),
  ('profile-images', 'profile-images', true, 5242880, array['image/jpeg', 'image/png', 'image/webp', 'image/avif', 'image/gif']),
  ('project-images', 'project-images', true, 5242880, array['image/jpeg', 'image/png', 'image/webp', 'image/avif', 'image/gif'])
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;
